In [1]:
import pandas as pd

In [2]:
# Dataset source URL
url = "https://raw.githubusercontent.com/data-bootcamp-v4/prework_data/main/students_performance.csv"

In [3]:
df =pd.read_csv(url)

In [4]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
# 3. Explore the dataset

# Number of rows and columns
print("Shape of the dataset (rows, columns):", df.shape)

Shape of the dataset (rows, columns): (1000, 8)

In [6]:
# Number of unique values in each column
print("\nNumber of unique values in each column:")
print(df.nunique())

Number of unique values in each column:
gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [7]:
# For columns with less than 10 distinct values, show unique values
print("\nUnique values in columns with less than 10 distinct values:")
for column in df.columns:
    if df[column].nunique() < 10:
        print(f"\nColumn: {column}")
        print(df[column].unique())

Unique values in columns with less than 10 distinct values:

Column: gender
['female' 'male']

Column: race/ethnicity
['group B' 'group C' 'group A' 'group D' 'group E']

Column: parental level of education
["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

Column: lunch
['standard' 'free/reduced']

Column: test preparation course
['none' 'completed']

In [8]:
# 4. Analyze Descriptive Statistics

print("\n--- Descriptive Statistics for Numerical Variables ---")

# Numerical variables
numerical_cols = ['math score', 'reading score', 'writing score']

# Central Tendency Measures
for col in numerical_cols:
    print(f"\nStatistics for {col}:")
    print(f"Mean: {df[col].mean()}")
    print(f"Median: {df[col].median()}")
    print(f"Mode: {df[col].mode().values[0]}")
    print(f"Standard Deviation: {df[col].std()}")
    print(f"Range: {df[col].max() - df[col].min()}")

print("\n--- Frequency Counts for Categorical Variables ---")

--- Descriptive Statistics for Numerical Variables ---

Statistics for math score:
Mean: 66.089
Median: 66.0
Mode: 65
Standard Deviation: 15.163080096009468
Range: 100

Statistics for reading score:
Mean: 69.169
Median: 70.0
Mode: 72
Standard Deviation: 14.60019193725222
Range: 83

Statistics for writing score:
Mean: 68.054
Median: 69.0
Mode: 74
Standard Deviation: 15.195657010869642
Range: 90

--- Frequency Counts for Categorical Variables ---

In [9]:
# Categorical variables
categorical_cols = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

for col in categorical_cols:
    print(f"\nValue counts for {col}:")
    print(df[col].value_counts())

Value counts for gender:
gender
female    518
male      482
Name: count, dtype: int64

Value counts for race/ethnicity:
race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

Value counts for parental level of education:
parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

Value counts for lunch:
lunch
standard        645
free/reduced    355
Name: count, dtype: int64

Value counts for test preparation course:
test preparation course
none         642
completed    358
Name: count, dtype: int64